jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: '3.7'
    - continue-on-error: true
      name: Install Python dependencies
      run: 'pip install -U --user wheel

        '
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: build
      run: 'mvn -B install -pl ${{ matrix.modules }} -am -DskipTests -Dfast -Pinstall-py-dep

        '
    - continue-on-error: true
      env:
        TF_ON_FLINK_IP: 127.0.0.1
      name: test
      run: 'mvn -B test -pl ${{ matrix.modules }}

        '
    strategy:
      fail-fast: false
      matrix:
        modules:
        - dl-on-flink-framework
        - dl-on-flink-operator
        - dl-on-flink-tensorflow-common
        - dl-on-flink-tensorflow
        - dl-on-flink-tensorflow-2.x
        - dl-on-flink-pytorch
        - dl-on-flink-lib
        - dl-on-flink-examples
        - dl-on-flink-examples/dl-on-flink-examples-pytorch
        - dl-on-flink-examples/dl-on-flink-examples-tensorflow
        - dl-on-flink-examples/dl-on-flink-examples-tensorflow-2.x
  build-and-test-python:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: '3.7'
    - continue-on-error: true
      name: Install Python dependencies
      run: 'pip install -U --user wheel

        '
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: build
      run: 'mvn -B install -pl ${{ matrix.modules }} -am -DskipTests -Dfast -Pinstall-py-dep

        '
    - continue-on-error: true
      name: test
      run: 'cd ${{ matrix.modules }}/python

        pip install -e .

        python -m unittest discover -v .

        '
    strategy:
      fail-fast: false
      matrix:
        modules:
        - dl-on-flink-framework
        - dl-on-flink-tensorflow
        - dl-on-flink-tensorflow-2.x
        - dl-on-flink-pytorch
name: Build And Test
on:
  repository_dispatch:
    types: trigger-ga___build-and-test.yaml
